services:
  posts-service:
    build: posts/.
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-service
      - users-service

  users-service:
    build: users/.
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-service

  postgres-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=spring-microservices-users-posts-73
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
